### ISSUE TITLE
403 Client Error: Site Disabled for url

### ISSUE THREAD

**Issue by Danielv123** [marhoy/nrk-download#17]
**Describe the bug**

**To Reproduce**

run `nrkdownload https://tv.nrk.no/serie/newton`

**Expected behavior**

Series starts downloading

**Observed behaviour**

`Traceback (most recent call last):
  File "c:\users\danielv\appdata\local\programs\python\python38-32\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\danielv\appdata\local\programs\python\python38-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\danielv\AppData\Roaming\Python\Python38\Scripts\nrkdownload.exe\__main__.py", line 9, in <module>
  File "C:\Users\danielv\AppData\Roaming\Python\Python38\site-packages\nrkdownload\commandline_script.py", line 80, in main
    download_url(url, download_all=arguments.all, download_last=arguments.last)
  File "C:\Users\danielv\AppData\Roaming\Python\Python38\site-packages\nrkdownload\commandline_script.py", line 95, in download_url
    programs = parse_nrk_url.parse_url(url)
  File "C:\Users\danielv\AppData\Roaming\Python\Python38\site-packages\nrkdownload\parse_nrk_url.py", line 113, in parse_url
    series = tv.series_from_series_id(series_id)
  File "C:\Users\danielv\AppData\Roaming\Python\Python38\site-packages\nrkdownload\tv.py", line 281, in series_from_series_id
    json = nrkapi.get_series(series_id)
  File "C:\Users\danielv\AppData\Roaming\Python\Python38\site-packages\nrkdownload\nrkapi.py", line 94, in get_series
    r.raise_for_status()
  File "C:\Users\danielv\AppData\Roaming\Python\Python38\site-packages\requests\models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Site Disabled for url: http://psapi3-webapp-prod-we.azurewebsites.net/series/newton`

**Desktop (please complete the following information):**
 - OS: windows 10
 - Version 2.0.3

**Additional context**

**Comment by marhoy** [comment]
NRK seems to have changed / updated their API.
I will have to look at it and update the code. Hopefully, we can still make this work.

**Comment by marhoy** [comment]
This issue should be solved in the new release 2.1.1.
Please update and retry
