### ISSUE TITLE
NRK Radio broken for me

### ISSUE THREAD

**Issue by nurk39** [marhoy/nrk-download#19]
**Describe the bug**

When trying to download a episode of old "Stompa" show nrkdownload gives stacktrace.

**To Reproduce**
```
$ nrkdownload -d . https://radio.nrk.no/serie/stompa/MKTT60001160/27-08-1960
Traceback (most recent call last):
  File "/usr/local/bin/nrkdownload", line 11, in <module>
    sys.exit(main())
  File "/home/janl/.local/lib/python3.6/site-packages/nrkdownload/commandline_script.py", line 105, in main
    download_url(url, download_all=arguments.all, download_last=arguments.last)
  File "/home/janl/.local/lib/python3.6/site-packages/nrkdownload/commandline_script.py", line 121, in download_url
    programs = parse_nrk_url.parse_url(url)
  File "/home/janl/.local/lib/python3.6/site-packages/nrkdownload/parse_nrk_url.py", line 80, in parse_url
    episode = tv.new_program_from_mediaelement_id(media_id)
  File "/home/janl/.local/lib/python3.6/site-packages/nrkdownload/tv.py", line 298, in new_program_from_mediaelement_id
    episode_title=episode_title,
  File "/home/janl/.local/lib/python3.6/site-packages/nrkdownload/tv.py", line 69, in __init__
    self._series = series_from_series_id(self.series_id)
  File "/home/janl/.local/lib/python3.6/site-packages/nrkdownload/tv.py", line 310, in series_from_series_id
    json = nrkapi.get_series(series_id)
  File "/home/janl/.local/lib/python3.6/site-packages/nrkdownload/nrkapi.py", line 106, in get_series
    r.raise_for_status()
  File "/home/janl/.local/lib/python3.6/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://psapi.nrk.no/tv/catalog/series/stompa

$ host psapi.nrk.no
psapi.nrk.no is an alias for psapi3-prod.trafficmanager.net.
psapi3-prod.trafficmanager.net is an alias for gateway-prod-we1.westeurope.cloudapp.azure.com.
gateway-prod-we1.westeurope.cloudapp.azure.com has address 13.81.172.33
```
The psapi.nrk.no URL gives a 404.

**Expected behavior**
No exceptions thrown

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux
 - Ubuntu 18.04.4 LTS

**Additional context**
 - Version nrkdownload version 2.1.2, running under Linux with Python 3.6.9
 - Works on TV shows

**Comment by marhoy** [comment]
Yes, I'm aware of the problem.
Radio content have not been working since NRK changed their API in April.
But I'll give it a second try :)

**Comment by arthoz** [comment]
Any updates to this issue?

**Comment by marhoy** [comment]
No, I'm sorry to say that I haven't had time to look at this for a long time.
Maybe I'll have some spare time during Christmas, we'll see :)

**Comment by tobixen** [comment]
Still an issue ... 

```
$ nrkdownload https://radio.nrk.no/serie/i-trifidenes-dager/
Not able to parse URL
```

**Comment by eivindlm** [comment]
I would also be very interested in the feature to download content from radio, actually both "Stompa" as @nurk39 mentions, and "I Trifidenes Dager" as @tobixen mentions.

@marhoy unless you happen to find time to look at this yourself, perhaps you could share some ideas/thoughts/pointers that could help other developers to contribute?
