### ISSUE TITLE
Some series report as "Not available for download" even if they work in browser

### ISSUE THREAD

**Issue by mstormo** [marhoy/nrk-download#21]
Using current version (2.1.2), using Python 3.8.3, via VPN to Oslo.

Example URLs not working:
    "https://tv.nrk.no/serie/klassen/sesong/1"
    "https://tv.nrk.no/serie/exit/sesong/1/"

While these work
    "https://tv.nrk.no/serie/newton/2021"
    "https://tv.nrk.no/serie/superkrim/sesong/10"

__Note that all links work in the browser with VPN on, just not through the nrk-downloader script.__
Any idea what to look for in the code to get a clue as to what's going on?

Some logging issue with double -v:
```
[DEBUG] nrkdownload.nrkapi(104): Getting json-data on series exit
--- Logging error ---
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\logging\__init__.py", line 1081, in emit
    msg = self.format(record)
  File "c:\programdata\anaconda3\lib\logging\__init__.py", line 925, in format
    return fmt.format(record)
  File "c:\programdata\anaconda3\lib\logging\__init__.py", line 664, in format
    record.message = record.getMessage()
  File "c:\programdata\anaconda3\lib\logging\__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not enough arguments for format string
Call stack:
  File "c:\programdata\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\programdata\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\Scripts\nrkdownload.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "c:\programdata\anaconda3\lib\site-packages\nrkdownload\commandline_script.py", line 105, in main
    download_url(url, download_all=arguments.all, download_last=arguments.last)
  File "c:\programdata\anaconda3\lib\site-packages\nrkdownload\commandline_script.py", line 121, in download_url
    programs = parse_nrk_url.parse_url(url)
  File "c:\programdata\anaconda3\lib\site-packages\nrkdownload\parse_nrk_url.py", line 108, in parse_url
    series = tv.series_from_series_id(series_id)
  File "c:\programdata\anaconda3\lib\site-packages\nrkdownload\tv.py", line 330, in series_from_series_id
    seasons[season_id] = Season(
  File "c:\programdata\anaconda3\lib\site-packages\nrkdownload\tv.py", line 182, in __init__
    LOG.debug("Creating new season of %s: %s: %s: %s", series_id, season_id, name)
Message: 'Creating new season of %s: %s: %s: %s'
Arguments: ('exit', '1', '1')
--- Logging error ---
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\logging\__init__.py", line 1081, in emit
    msg = self.format(record)
  File "c:\programdata\anaconda3\lib\logging\__init__.py", line 925, in format
    return fmt.format(record)
  File "c:\programdata\anaconda3\lib\logging\__init__.py", line 664, in format
    record.message = record.getMessage()
  File "c:\programdata\anaconda3\lib\logging\__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not enough arguments for format string
Call stack:
  File "c:\programdata\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\programdata\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\Scripts\nrkdownload.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "c:\programdata\anaconda3\lib\site-packages\nrkdownload\commandline_script.py", line 105, in main
    download_url(url, download_all=arguments.all, download_last=arguments.last)
  File "c:\programdata\anaconda3\lib\site-packages\nrkdownload\commandline_script.py", line 121, in download_url
    programs = parse_nrk_url.parse_url(url)
  File "c:\programdata\anaconda3\lib\site-packages\nrkdownload\parse_nrk_url.py", line 108, in parse_url
    series = tv.series_from_series_id(series_id)
  File "c:\programdata\anaconda3\lib\site-packages\nrkdownload\tv.py", line 330, in series_from_series_id
    seasons[season_id] = Season(
  File "c:\programdata\anaconda3\lib\site-packages\nrkdownload\tv.py", line 182, in __init__
    LOG.debug("Creating new season of %s: %s: %s: %s", series_id, season_id, name)
Message: 'Creating new season of %s: %s: %s: %s'
Arguments: ('exit', '2', '2')
```

**Comment by magnusgundersen** [comment]
I'm having the same issue, however not using VPN. 

Might be due to copyright issues? The examples https://github.com/marhoy/nrk-download/blob/master/docs/50_examples.rst in this repo gives the following explanation for this issue:
"Due to copyright-issues, some of the episodes might not be available for
download"
