### ISSUE TITLE
KeyError: 'titles'

### ISSUE THREAD

**Issue by tordenflesk** [marhoy/nrk-download#23]
λ nrkdownload.exe https://radio.nrk.no/podkast/radioresepsjonen/
Traceback (most recent call last):
  File "c:\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python38\Scripts\nrkdownload.exe\__main__.py", line 7, in <module>
  File "c:\python38\lib\site-packages\nrkdownload\commandline_script.py", line 105, in main
    download_url(url, download_all=arguments.all, download_last=arguments.last)
  File "c:\python38\lib\site-packages\nrkdownload\commandline_script.py", line 121, in download_url
    programs = parse_nrk_url.parse_url(url)
  File "c:\python38\lib\site-packages\nrkdownload\parse_nrk_url.py", line 146, in parse_url
    podcast = radio.podcast_from_podcast_id(podcast_id)
  File "c:\python38\lib\site-packages\nrkdownload\radio.py", line 95, in podcast_from_podcast_id
    title = json["titles"]["title"].strip()
KeyError: 'titles'

**Comment by marhoy** [comment]
Yes, podcasts/radio is not supported at the moment.
