### ISSUE TITLE
Cannot download news

### ISSUE THREAD

**Issue by balta2ar** [marhoy/nrk-download#24]
Has their API changed? Or they moved somewhere else?
```
$ nrkdownload -d . 'https://tv.nrk.no/serie/distriktsnyheter-nordland/202203/DKNO98031522/avspiller'
Traceback (most recent call last):
  File "/home/bz/.local/bin/nrkdownload", line 8, in <module>
    sys.exit(main())
  File "/home/bz/.local/lib/python3.10/site-packages/nrkdownload/commandline_script.py", line 105, in main
    download_url(url, download_all=arguments.all, download_last=arguments.last)
  File "/home/bz/.local/lib/python3.10/site-packages/nrkdownload/commandline_script.py", line 121, in download_url
    programs = parse_nrk_url.parse_url(url)
  File "/home/bz/.local/lib/python3.10/site-packages/nrkdownload/parse_nrk_url.py", line 80, in parse_url
    episode = tv.new_program_from_mediaelement_id(media_id)
  File "/home/bz/.local/lib/python3.10/site-packages/nrkdownload/tv.py", line 273, in new_program_from_mediaelement_id
    json = nrkapi.get_mediaelement(mediaelement_id)
  File "/home/bz/.local/lib/python3.10/site-packages/nrkdownload/nrkapi.py", line 71, in get_mediaelement
    r.raise_for_status()
  File "/home/bz/.local/lib/python3.10/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 410 Client Error: Gone for url: http://psapi-granitt-prod-we.cloudapp.net/mediaelement/DKNO98031522
```

**Comment by marhoy** [comment]
I just released version 3.0.0, a complete rewrite from scratch.
Can you give that a try?
Please note that it's been simplified a bit, please read updated documenation.

**Comment by balta2ar** [comment]
Thank you for putting effort into making a new version!

I've just tried it again and it seems to download many news episodes, whereas I'd like it to download only one, e.g.
```
nrkdownload -d . 'https://tv.nrk.no/serie/distriktsnyheter-nordland/202204/DKNO98042722'
```

**Comment by marhoy** [comment]
Hehe, single episode download of a series is not implemented yet: You get at least a season (which is 1 month for news series)...

At least, the episode you want will be one of those 😊


Mvh,

Martin
-- 
Sendt fra iPhone

**Comment by marhoy** [comment]
Version 3.1.0 adds the possibility to download single episodes from a series.
So in your example, only the episode from April 27th 2022.

(Note that recent news-episodes have names like "Mandag...", but after a while the name is changed to a date).

**Comment by balta2ar** [comment]
Tusen hjertelig takk!
