### ISSUE TITLE
Unable to download series with "?" in title.

### ISSUE THREAD

**Issue by ksolheim** [marhoy/nrk-download#27]
**Describe the bug**
Fails to download titles with "?" in title on Windows 10.

**To Reproduce**
1. nrkdownload.exe -d D:\temp\ https://tv.nrk.no/serie/skal-vi-lekee

**Expected behavior**
Download as normal.

**Error**
```
PS C:\Users\default> nrkdownload.exe -d D:\temp\ https://tv.nrk.no/serie/skal-vi-lekee
Downloading Skal vi leke?
Downloading Sesong 1
  [------------------------------------]    0%
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\users\default\.local\bin\nrkdownload.exe\__main__.py", line 7, in <module>
  File "C:\Users\default\.local\pipx\venvs\nrkdownload\lib\site-packages\typer\main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "C:\Users\default\.local\pipx\venvs\nrkdownload\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\default\.local\pipx\venvs\nrkdownload\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\default\.local\pipx\venvs\nrkdownload\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\default\.local\pipx\venvs\nrkdownload\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\default\.local\pipx\venvs\nrkdownload\lib\site-packages\typer\main.py", line 532, in wrapper
    return callback(**use_params)  # type: ignore
  File "C:\Users\default\.local\pipx\venvs\nrkdownload\lib\site-packages\nrkdownload\cli.py", line 89, in main
    download_series(download_dir, series_id, season_id, episode_id)
  File "C:\Users\default\.local\pipx\venvs\nrkdownload\lib\site-packages\nrkdownload\download.py", line 73, in download_series
    program.download_as_episode(series.title, sequence_string, directory)
  File "C:\Users\default\.local\pipx\venvs\nrkdownload\lib\site-packages\nrkdownload\nrk_tv.py", line 97, in download_as_episode
    download_image_url(self.image_url, Path(f"{filename}.jpg"))
  File "C:\Users\default\.local\pipx\venvs\nrkdownload\lib\site-packages\nrkdownload\nrk_tv.py", line 36, in download_image_url
    with open(filename, "wb") as file:
OSError: [Errno 22] Invalid argument: 'D:\\temp\\Skal vi leke\\Season 01\\Skal vi leke? - s01e01 - 1. Hund.jpg'

```
**Desktop (please complete the following information):**
 - OS: Windows 10 21H2
 - Python 3.10.5
 - Installed nrk-download via pipx

**Comment by marhoy** [comment]
Fixed by #28, available in version 3.1.1.
Please upgrade your installation by saying `pipx upgrade nrkdownload`
